// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4qLb0dng6_DOdVOYtBVZ4A_AXDe6qN70',
    appId: '1:249366730872:web:9ac5680510953dd7b0f58d',
    messagingSenderId: '249366730872',
    projectId: 'drfootapp-2a1c8',
    authDomain: 'drfootapp-2a1c8.firebaseapp.com',
    storageBucket: 'drfootapp-2a1c8.appspot.com',
    measurementId: 'G-5VDVY225F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL2Th_cowV21x4ryJ1cdvobTD8rZF5E68',
    appId: '1:249366730872:android:f0e66b6038be3408b0f58d',
    messagingSenderId: '249366730872',
    projectId: 'drfootapp-2a1c8',
    storageBucket: 'drfootapp-2a1c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASoeR1wMK-OlTSoET5axdKJtZMmL1wQI0',
    appId: '1:249366730872:ios:6dd19785c5d69650b0f58d',
    messagingSenderId: '249366730872',
    projectId: 'drfootapp-2a1c8',
    storageBucket: 'drfootapp-2a1c8.appspot.com',
    iosBundleId: 'com.drfootapp',
  );
}
